name: GitHub Breakout
on:
  schedule:
    - cron: "0 0 * * *"         # Runs daily at midnight
  workflow_dispatch:           # Manual trigger option

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # Allows action to push generated files
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Breakout SVGs
        uses: cyprieng/github-breakout@v1.0.0
        with:
          github_username: ${{ github.repository_owner }}

      - name: Move SVGs to images folder
        run: |
          mkdir -p images
          mv output/light.svg images/breakout-light.svg
          mv output/dark.svg images/breakout-dark.svg

      - name: Commit & push SVGs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add images/breakout-light.svg images/breakout-dark.svg
          git commit -m "chore: update breakout SVGs" || echo "No changes to commit"
          git push
