# name: Generate Snake

# on:
#   schedule: # Run every 24 hours
#     - cron: "0 0 * * *"
#   workflow_dispatch: # Allow manual trigger

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Generate Snake Animation
#         uses: Platane/snk@v3
#         with:
#           github_user_name: omprakashbabu
#           outputs: |
#             dist/github-contribution-grid-snake.svg
#             dist/github-contribution-grid-snake-dark.svg?palette=github-dark

#       - name: Push to GitHub
#         uses: crazy-max/ghaction-github-pages@v3.1.0
#         with:
#           target_branch: output
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight
  workflow_dispatch: # allow manual runs
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: omprakashbabu
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
